name: Update data

on:
  schedule:
    - cron: 0 */3 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify
        env:
          NETLIFY_TRIGGER_KEY: ${{ secrets.NETLIFY_TRIGGER_KEY }}
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_TRIGGER_KEY